name: example
description: Example app that consumes the design system (ds_components).
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  ds_components: ^0.1.0
  ds_foundation: ^0.1.0
  flutter:
    sdk: flutter
  material_ui: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
