import 'package:flutter/widgets.dart';

import 'ds_colors.dart';
import 'ds_icons.dart';
import 'ds_metrics.dart';
import 'ds_motion.dart';
import 'ds_shadows.dart';
import 'ds_type.dart';

/// The values a design system's `tokens.json` defines. Generated by
/// `tool/gen_tokens.dart`; never written by hand.
@immutable
class DsTokenSet {
  const DsTokenSet({
    required this.name,
    required this.colorsLight,
    required this.colorsDark,
    required this.shadowsLight,
    required this.shadowsDark,
    required this.type,
    required this.spacing,
    required this.radii,
    required this.sizes,
    required this.opacity,
  });

  final String name;
  final DsColors colorsLight;
  final DsColors colorsDark;
  final DsShadows shadowsLight;
  final DsShadows shadowsDark;
  final DsTypeScale type;
  final DsSpacing spacing;
  final DsRadii radii;
  final DsSizes sizes;
  final DsOpacities opacity;
}

/// Corner geometry of a system.
enum DsCorners {
  /// Continuous corners (Pebble).
  superellipse,

  /// Circular arcs.
  circular,
}

/// A complete design system: generated [tokens] plus the choices tokens.json
/// cannot express (faces, motion, icons, corners). Switching the app's
/// design system means passing another [DsSystem] to `DsTheme`.
@immutable
class DsSystem {
  const DsSystem({
    required this.tokens,
    required this.fonts,
    required this.motion,
    required this.icons,
    this.corners = DsCorners.superellipse,
    this.haptics = true,
  });

  final DsTokenSet tokens;
  final DsFonts fonts;
  final DsMotion motion;
  final DsIconSet icons;
  final DsCorners corners;

  /// Whether components fire haptics at all.
  final bool haptics;

  String get name => tokens.name;

  /// The same system with other values, e.g. a brand that keeps Pebble but
  /// changes its faces or icon set.
  DsSystem copyWith({
    DsTokenSet? tokens,
    DsFonts? fonts,
    DsMotion? motion,
    DsIconSet? icons,
    DsCorners? corners,
    bool? haptics,
  }) => DsSystem(
    tokens: tokens ?? this.tokens,
    fonts: fonts ?? this.fonts,
    motion: motion ?? this.motion,
    icons: icons ?? this.icons,
    corners: corners ?? this.corners,
    haptics: haptics ?? this.haptics,
  );

  /// A rounded shape in this system's corner geometry.
  OutlinedBorder shape(BorderRadiusGeometry radius, {BorderSide? side}) =>
      switch (corners) {
        DsCorners.superellipse => RoundedSuperellipseBorder(
          borderRadius: radius,
          side: side ?? BorderSide.none,
        ),
        DsCorners.circular => RoundedRectangleBorder(
          borderRadius: radius,
          side: side ?? BorderSide.none,
        ),
      };
}
